sudo: required
language: generic
services:
  - docker

# before_install:
#       - docker build -t ropenflash/

script:
  - echo "hello"

after_success:
  - docker build -t ropenflash/multi-client ./client
  - docker build -t ropenflash/multi-nginx ./nginx
  - docker build -t ropenflash/multi-server ./server
  - docker build -t ropenflash/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ropenflash/multi-client
  - docker push ropenflash/multi-nginx
  - docker push ropenflash/multi-server
  - docker push ropenflash/multi-worker
