version: "3.0"
services:
  client:
    image: ropenflash/multi-client
    container_name: client
  api:
    image: ropenflash/multi-server
    container_name: server
    volumes:
      - /app/node_modules
      - ./server/:/app
    depends_on:
      - postgresdb
      - redis
    environment:
      - PGUSER=postgres
      - PGHOST=postgresdb
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
      - CHOKIDAR_USEPOLLING=true
  worker:
    image: ropenflash/multi-worker
    container_name: worker
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHOKIDAR_USEPOLLING=true
  postgresdb:
    image: postgres:13.1-alpine
    container_name: database
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    container_name: redis-cache
  nginx:
    image: ropenflash/multi-nginx
    restart: always
    ports:
      - 8080:80
    depends_on:
      - client
      - api
    container_name: router
